### ISSUE TITLE
comes with a virus

### ISSUE THREAD

**Issue by bestenfallskongenial** [Merutochan/glitchGBA#1]
compile.exe is infested:)

**Comment by merumerutho** [comment]
Autoit compiled .exes (especially when they delete files and launch other executables) are famously known for being flagged automatically by software antiviruses (whose heuristics I really wonder about, sometimes).
There is nothing malicious about the executable. It is simply the compiled version of the .au3 script included.

I do understand that the decision, at the time, of creating an Autoit script and including its compiled executable to automate the picture conversion and ROM compilation process was rather dull compared to simply using another scripting language. The reason why it wasn't done in Python or through makefile batch commands, is simply because of a 'skill' issue. At the time of creating the project, I was not used to using python for these sort of operations, leading to the decision of using what I knew at the time: Autoit, that is.

If it can be helpful, I'll work on an update where the Autoit script and its compiled .exe version are removed, and a python script is included instead.
